In [2]:
import numpy as np

english_score = np.array([55, 89, 76, 65, 48, 70])
math_score = np.array([60, 85, 60, 68, np.nan, 60])
chinese_score = np.array([65, 90, 82, 72, 66, 77])

In [3]:
all_score = np.vstack((english_score, math_score, chinese_score))     #成績合併
all_score

array([[55., 89., 76., 65., 48., 70.],
       [60., 85., 60., 68., nan, 60.],
       [65., 90., 82., 72., 66., 77.]])

In [4]:
print(np.nanmean(all_score, axis=1).round(1))       
print(np.nanmax(all_score, axis=1))
print(np.nanmin(all_score, axis=1))
print(np.nanstd(all_score, axis=1).round(1))

[67.2 66.6 75.3]
[89. 85. 90.]
[48. 60. 65.]
[13.4  9.7  8.8]


In [5]:
math_score[4]=55
all_score = np.vstack((english_score, math_score, chinese_score)) 
print(all_score)

[[55. 89. 76. 65. 48. 70.]
 [60. 85. 60. 68. 55. 60.]
 [65. 90. 82. 72. 66. 77.]]


In [6]:
print(np.mean(math_score).round(1))       
print(np.max(math_score))
print(np.min(math_score))
print(np.std(math_score).round(1))

64.7
85.0
55.0
9.9


In [9]:
print(np.corrcoef(all_score).round(2))    # 英文＿數學＿國文
print("跟國文最相關的是英文：", 0.978)

[[1.   0.79 0.98]
 [0.79 1.   0.74]
 [0.98 0.74 1.  ]]
跟國文最相關的是英文： 0.978
